# Generated by Django 3.1 on 2020-08-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200811_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='purchaseno',
            field=models.IntegerField(default=1),
        ),
    ]
