# Generated by Django 3.1 on 2020-08-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_billitemstest2_billtest2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='batch_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productdetailbatch',
            name='packing',
            field=models.CharField(default='', max_length=50),
        ),
    ]
